.travis.yml, package.json
=> first test

client/app.js, client/components/Map.js, client/components/SimpleContainer.js, package-lock.json, package.json, public/index.html
=> material stuff, got a container loading

client/components/Map.js, package-lock.json, package.json, server/api/google.js, server/api/index.js
=> node google api working

server/db/models/index.js, server/db/models/journey.js, server/db/models/journeyCategory.js, server/db/models/place.js, server/db/models/placeCategory.js, server/db/models/segment.js
---
set up database models skeleton
=> models skeleton

server/api/journeys-categories.js, server/api/journeys.js, server/api/places-categories.js, server/api/places.js, server/api/segments.js, server/api/users.js
---
express routes skeleton set up
=> express routes skeleton set up

client/app.js, client/components/MapDirections.js, package-lock.json
=> got directions working!!!!

client/app.js, client/components/MapDirections.js
=> multiple routes rendering

client/app.js, client/components/Map.js, client/components/MapContainer.js, client/components/MapDirections.js, client/components/RouteView.js
=> unrecomposed

client/app.js, client/components/Map.js, package.json
=> got a search bar!

client/components/Map.js, client/components/MapDirections.js
=> removed-satellite!

client/components/RouteView.js, package-lock.json
=> resolved error

client/components/MapContainer.js, client/components/RouteView.js, client/hooks-store/hooksStore.js
=> more stuff

client/components/Map.js, client/components/MapContainer.js, client/components/RouteList.js
=> searchbox experimental

client/components/Login.js, client/components/Map.js, client/components/MapContainer.js, client/hooks-store/rootReducer.js, client/hooks-store/search/searchReducer.js
=> search input clears after adding place

client/components/Map.js, client/components/RouteList.js, client/components/RouteView.js, client/utils/saveJourney.js, server/api/index.js, server/api/journeys.js, server/api/segments.js, server/db/models/index.js, server/db/models/journey.js, server/db/models/place.js, server/db/models/segment.js
=> Posting journeys db

package-lock.json, script/seed.js, server/api/segments.js
---
3 journeys with 4 segments each
=> seed file created through postman

client/components/CommandBar.js, client/components/Map.js, client/components/MapContainer.js, client/utils/saveJourney.js, script/seed.js
=> Save journey

client/components/Map.js, client/components/MarkerView.js, client/components/RouteView.js, client/hooks-store/places/placesReducer.js, client/hooks-store/search/searchReducer.js, client/hooks-store/segments/segmentsReducer.js, client/utils/directions.js
=> fixed delete

client/components/CommandBar.js, client/components/MarkerView.js
---
Marker Color working, can add custom SVG if we like.
=> Marker colors & custom icons working

client/components/Map.js
=> userLocation rendering

client/components/Map.js, client/components/MapControl.js
---
MapControl.js component renders children HTML directly on map (including buttons). Using component to render "Me" button that centers map on users Location.
=> map options component added

client/components/Map.js, public/index.html
---
added various mobile QoL improvements
=> single finger scroll, search input optimization, disabled zoom on page

client/components/CommandBar.js, client/components/Map.js, client/components/MapContainer.js, client/components/MarkerView.js, client/hooks-store/places/placesReducer.js, client/hooks-store/rootReducer.js, client/hooks-store/search/placesService.js, client/utils/saveJourney.js, script/seed.js, server/db/models/place.js
=> Markers on multi journey

client/app.js, client/hooks-store/places/placesReducer.js, client/hooks-store/segments/segmentsReducer.js, client/utils/deletePlace.js
=> place delete bug fixed

client/app.js, client/components/JourneysList.js
=> can see list of journeys

client/components/MapContainer.js, client/utils/mapStyle.js
=> map styled

client/components/HomePage.js, client/components/JourneysList.js, client/components/MapContainer.js, client/components/RouteList.js
=> Move save button

client/components/PlacePreview.js
=> save notification

client/components/MarkerView.js, client/components/RouteList.js, client/components/RouteView.js, script/seed.js
=> Dress rehersal

client/app.js, client/components/HomePage.js, client/components/Map.js, client/components/MapContainer.js, client/components/NavBar/AppBar.js, client/components/RouteList.js
=> R list styles

client/components/RouteList.js
=> added img spacing

client/components/MapContainer.js, client/components/RouteList.js
=> removed list padding

client/components/MapContainer.js, client/components/RouteList.js
=> more list styling

client/components/PlacePreview.js
=> placePreview Styling

client/components/RouteList.js, client/hooks-store/places/placesReducer.js, client/hooks-store/segments/segmentsReducer.js
=> fixed delete places bug

client/components/JourneysList.js, client/components/RouteList.js, client/hooks-store/segments/segmentsReducer.js, client/utils/singleJourneyPlaces.js
=> Deleting bug

client/components/JourneysList.js, client/hooks-store/segments/segmentsReducer.js, client/utils/singleJourneyPlaces.js
=> colors coordinate!!

client/components/JourneysList.js, client/components/MapContainer.js, client/components/RouteList.js
=> made width styling fit for device

client/components/Map.js, client/components/NavBar/AppBar.js, client/components/PlacePreview.js, client/hooks-store/places/placesReducer.js, client/hooks-store/search/boundsReducer.js, client/hooks-store/search/centerReducer.js, client/hooks-store/segments/segmentsReducer.js, client/utils/deletePlace.js
=> segment bug fixed

client/index.js, public/service-worker.js, webpack.config.js
=> Service worker

.travis.yml
Trying to fix travis CI to deploy to heroku.
=> trying to fix travis-heroku deploy

.travis.yml
=> trying to fix travis

client/components/Map.js
---
Retrieving the bounds for route segments was crashing the app. I updated the bounds getters.
=> fixed setting bounds on route segments

client/components/HomePage.js, client/components/JourneysList.js, client/components/MapContainer.js, client/components/RouteList.js
---
JourneyList width now fills.
=> tweaked journeyList to fill width
